### ISSUE TITLE
Release numbers went backwards: 1.6.3 is after 3.0.2

### ISSUE THREAD

**Issue by yurivict** [coin-or-tools/ThirdParty-Mumps#7]

**Comment by tkralphs** [comment]
We use semantic versioning and may continue to support and patch older stable (major.minor) versions. The relative timing of patch releases in different stable series doesn't have any meaningful interpretation. `1.6.3` is a patch release for an older stable version (`1.6`) that we are still supporting. The fact that it came after `3.0.2` in real time is not really a problem, it's by design.

**Comment by yurivict** [comment]
Ok, thanks.
